### PR TITLE
GUI for different prediction tasks

### PR DESCRIPTION
**Pull request by arielclj**

### CODE REVIEW

**Comment by chrishkchris** [comment]
@arielclj 
From your code, there is a line
`import ForkbaseStatus from "../components/ForkbaseStatus"`
Is that your web page need forkbase for storage? 
https://github.com/arielclj/singa-easy/blob/master/predictionweb/src/ImageClassification/ImageClassification.js#L20

**Comment by nudles** [comment]
1. If we add a another task for object detection later, will there be a separate folder `objdetectionweb/`? Will it share some files with the `predictionweb/`?
2. we also need an index page which lists all available tasks and links them to the corresponding pages (predictionweb or objdetectionweb).
3. I suggest to organize the web code in this way

```
singa_easy/
            singa_easy/
            web/
                    index.html
                    tasks/
                               image_classification
                               object_detection
                               question_answering
                    xxxxx (some shared files among all the tasks)
```

**Comment by chrishkchris** [comment]
@arielclj 
Please take the following steps before I can merge the code:
1. Please rearrange to location of folders as methioned above
2. Remove all the "leftover code" of the last project you mentioned in the meeting
3. Host the web UI on ncrs, so I can help to verify on my browser
4. Add a .md file to show how to deploy

**Comment by chrishkchris** [comment]
I have merged Thao's Q&A UI, https://github.com/nusdbsystem/singa-easy/pull/6 , you can see if the model zoo can use Thao's Q&A web page, and build by the same yarn install yarn start

You may use git fetch or git pull to fetch the update from the nusdbsystem:master branch, so your branch will have Thao's update 

Your deployed UI: http://ncrs.d2.comp.nus.edu.sg:3002

**Comment by chrishkchris** [comment]
error
the lime and gradcam cannot display
the old UI has the same problem @naili-xing, so this is not the problem of this PR

**Comment by chrishkchris** [comment]
Her deployed UI is hosted on http://panda.d2.comp.nus.edu.sg:5000

Reminding task:
1. Include Q&A in the application zoo

**Comment by chrishkchris** [comment]
react app
the topic should be application zoo, but not react app, and I am not sure should keep the logo at singa-easy/web/public/logo192.png and logo512.png

**Comment by chrishkchris** [comment]
As informed by @arielclj, Ariel will need some extra time to modify the Q&A UI to make it compatiable with this application zoo React app

**Comment by chrishkchris** [comment]
@arielclj Please go into your github repo and merge this PR in your repo https://github.com/arielclj/singa-easy/pull/1
This is because some variable name has changed in the backend, your UI need this update to fetch the correct variable name
When you merge that PR, this PR will be updated automatically since they are refering to the same branch

**Comment by chrishkchris** [comment]
@arielclj  I put the inference job url here for you to test the Q&A UI ncrs.d2.comp.nus.edu.sg:3005/questionAnswer

**Comment by chrishkchris** [comment]
I merge this PR first, @arielclj will need to submit another PR to display the answer according to the following design
ddc70b5115e21f3b732ff542cff6170

**Pull request merged**
