### PR TITLE
Add dependences and solve some issues in model files as well as explanations' methods

### PR DESCRIPTION
**Pull request by NLGithubWP**

### CODE REVIEW

**Comment by nudles** [comment]
pls resolve the conflicts and fix the linting errors.

**Comment by chrishkchris** [comment]
@naili-xing 
I have updated your branch by pulling latest update in singa-easy repo, and resolved the minor conflicts
Please merge this one https://github.com/naili-xing/singa-easy/pull/1

Starting from next PR, should use git pull to fetch the latest update from nusdbsystem:master first, in order to remove the linting errors that are already fixed

**Comment by chrishkchris** [comment]
Now the conflict is resolved and the linting passed

**Comment by chrishkchris** [comment]
For verification, can you deploy the modified model and check if it is working?
Or you can deploy it and I help you to check

**Comment by chrishkchris** [comment]
I have verified the deployed model with @naili-xing, so the review is done. 
Ready for merge.

**Pull request merged**
